title: "ВЫБОРЫ - Технологии избирательных кампаний"
book_title: "ВЫБОРЫ - Технологии избирательных кампаний"
description: "Комплексное руководство по современным технологиям избирательных кампаний"
baseurl: "/Book-Elections"
url: "https://book.lemik.github.io"

# Feature flags
features:
  testimonials: false
  newsletter: false
  blog: false
  feedback: false

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  uk_posts:
    output: true
    permalink: /uk/:title/
  ru_posts:
    output: true
    permalink: /ru/:title/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md 
